apiVersion: v1
kind: Secret
metadata:
  name: gcp-helm-repo-secret
  namespace: argocd
  labels:
    # This label is MANDATORY for ArgoCD to recognize it as a repo
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  # The type must be 'helm' for OCI charts
  type: helm
  # This name is just a label in the UI
  name: boutique-charts
  # The exact URL of your Google Artifact Registry
  url: us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts
  # This MUST be "true" for Google Artifact Registry
  enableOCI: "true"
