apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tanya-domi/gitops-repo.git
    targetRevision: HEAD
    path: argocd-bootstrap
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  # apply this file manually in the cluster, It points to the argocd-bootstrap folder in GitHub repo.