apiVersion: v2
name: online-boutique-app #dev-env
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1
appVersion: "1.0.0" 

dependencies:
  - name: online-boutique-common
    version: 0.1.1
    repository: "oci://us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts"

  - name: cartservice
    version: 0.1.1
    repository: "oci://us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts"
    
  - name: currencyservice
    version: 0.1.1
    repository: "oci://us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts"
  
  - name: emailservice
    version: 0.1.1
    repository: "oci://us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts"
    
  - name: recommendationservice
    version: 0.1.1
    repository: "oci://us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts"
    
  - name: adservice
    version: 0.1.1
    repository: "oci://us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts"

  - name: loadgenerator 
    version: 0.1.1
    repository: "oci://us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts"

  - name: checkoutservice
    version: 0.1.1
    repository: "oci://us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts"
     
  - name: frontend
    version: 0.1.1
    repository: "oci://us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts"

  - name: shippingservice
    version: 0.1.1
    repository: "oci://us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts"

  - name: productcatalogservice
    version: 0.1.1
    repository: "oci://us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts"

  - name: paymentservice
    version: 0.1.1
    repository: "oci://us-central1-docker.pkg.dev/project-6b691de7-de66-4961-b80/helm-charts"
                
